import type { Practice } from '@/shared/types/practice';
import type { GeneratedQuestion } from '@/app/panel/lib/aiGenerator';

const SIMULATED_QUESTIONS: Record<string, GeneratedQuestion[]> = {
  'historia-nicaragua': [
    { question: '¿En que ano se independizo Nicaragua de Espana?', optionA: '1821', optionB: '1838', correctAnswer: 'A' },
    { question: '¿Quien fue el primer presidente de Nicaragua?', optionA: 'Jose Nunez', optionB: 'Francisco Hernandez', correctAnswer: 'A' },
    { question: '¿Cual es la capital de Nicaragua?', optionA: 'Managua', optionB: 'Leon', correctAnswer: 'A' },
    { question: '¿Que océano baña la costa oriental de Nicaragua?', optionA: 'Oceano Pacifico', optionB: 'Oceano Atlantico', correctAnswer: 'B' },
    { question: '¿En que ano se fundo la Universidad Nacional Autonoma de Nicaragua?', optionA: '1958', optionB: '1812', correctAnswer: 'A' },
    { question: '¿Que volcan es el mas alto de Nicaragua?', optionA: 'Concepcion', optionB: 'Mogoton', correctAnswer: 'B' },
    { question: '¿Cual es el lago mas grande de Centroamerica?', optionA: 'Lago de Atitlan', optionB: 'Lago Cocibolca', correctAnswer: 'B' },
    { question: '¿Que movimiento lidero Augusto C. Sandino?', optionA: 'Guerra contra la intervencion estadounidense', optionB: 'Reforma agraria', correctAnswer: 'A' },
    { question: '¿En que ano se fundo Managua como ciudad?', optionA: '1819', optionB: '1768', correctAnswer: 'A' },
    { question: '¿Que isla caribena pertenece a Nicaragua?', optionA: 'Isla de Ometepe', optionB: 'San Andres', correctAnswer: 'B' },
    { question: '¿Cual fue el nombre del periodo de la dictadura somocista?', optionA: 'La Era del Somocismo', optionB: 'La Epoca Dorada', correctAnswer: 'A' },
    { question: '¿En que ano cayo Anastasio Somoza Debayle?', optionA: '1979', optionB: '1967', correctAnswer: 'A' },
    { question: '¿Que río fluye por el Granada?', optionA: 'Rio Tipitapa', optionB: 'Rio San Juan', correctAnswer: 'A' },
    { question: '¿Que paso natural conecta los oceanos Atlantico y Pacifico en Nicaragua?', optionA: 'Canal de Nicaragua', optionB: 'Paso de Diriamba', correctAnswer: 'A' },
    { question: '¿Cual es el departamento mas grande de Nicaragua?', optionA: 'Zelaya', optionB: 'RACCN', correctAnswer: 'A' },
  ],
  'matematica-geometria': [
    { question: '¿Cual es la suma de los angulos internos de un triangulo?', optionA: '180 grados', optionB: '360 grados', correctAnswer: 'A' },
    { question: '¿Cuantos grados tiene un angulo recto?', optionA: '90 grados', optionB: '180 grados', correctAnswer: 'A' },
    { question: '¿Cual es la formula del area de un circulo?', optionA: 'pi * r^2', optionB: '2 * pi * r', correctAnswer: 'A' },
    { question: '¿Cuantos lados tiene un pentagono?', optionA: '5', optionB: '6', correctAnswer: 'A' },
    { question: '¿Que es la hipotenusa?', optionA: 'El lado mas largo de un triangulo rectangulo', optionB: 'El angulo mayor de un triangulo', correctAnswer: 'A' },
    { question: '¿Cual es el volumen de un cubo de lado 3?', optionA: '27', optionB: '9', correctAnswer: 'A' },
    { question: '¿Cuantos grados tiene un angulo llano?', optionA: '180 grados', optionB: '90 grados', correctAnswer: 'A' },
    { question: '¿Que figura geometrica tiene todos los lados iguales?', optionA: 'Cuadrado', optionB: 'Rectangulo', correctAnswer: 'A' },
    { question: '¿Cual es el perimetro de un cuadrado de lado 5?', optionA: '20', optionB: '25', correctAnswer: 'A' },
    { question: '¿Que es un poligono regular?', optionA: 'Tiene todos sus lados y angulos iguales', optionB: 'Tiene lados de diferentes longitudes', correctAnswer: 'A' },
  ],
  'ciencias-sistema-solar': [
    { question: '¿Cual es el planeta mas grande del sistema solar?', optionA: 'Jupiter', optionB: 'Saturno', correctAnswer: 'A' },
    { question: '¿Cuantos planetas tiene el sistema solar?', optionA: '8', optionB: '9', correctAnswer: 'A' },
    { question: '¿Que planeta es conocido como el planeta rojo?', optionA: 'Marte', optionB: 'Venus', correctAnswer: 'A' },
    { question: '¿Cual es la estrella mas cercana a la Tierra?', optionA: 'Sol', optionB: 'Proxima Centauri', correctAnswer: 'A' },
    { question: '¿Que planeta tiene los anillos mas visibles?', optionA: 'Saturno', optionB: 'Jupiter', correctAnswer: 'A' },
    { question: '¿En que planeta se encuentra el Gran Canyon Rojo?', optionA: 'Marte', optionB: 'Venus', correctAnswer: 'A' },
    { question: '¿Cual es la distancia media de la Tierra al Sol?', optionA: '150 millones de km', optionB: '300 millones de km', correctAnswer: 'A' },
    { question: '¿Que planeta gira en sentido contrario al demas?', optionA: 'Venus', optionB: 'Mercurio', correctAnswer: 'A' },
    { question: '¿Cual es el satelite natural de la Tierra?', optionA: 'Luna', optionB: 'Fobos', correctAnswer: 'A' },
    { question: '¿Que planeta tiene la temperatura mas baja?', optionA: 'Neptuno', optionB: 'Urano', correctAnswer: 'A' },
  ],
  'lengua-ortografia': [
    { question: '¿Como se escribe correctamnete?', optionA: 'Correctamente', optionB: 'Correctamante', correctAnswer: 'A' },
    { question: '¿Que palabra esta escrita correctamente?', optionA: 'Aunque', optionB: 'Anque', correctAnswer: 'A' },
    { question: '¿Donde lleva tilde la palabra "angulo"?', optionA: 'Angulo', optionB: 'Angülo', correctAnswer: 'A' },
    { question: '¿Cual es el plural correcto de "lapiz"?', optionA: 'Lapices', optionB: 'Lapizs', correctAnswer: 'A' },
    { question: '¿Como se escribe "hacia" o "hasia"?', optionA: 'Hacia', optionB: 'Hasia', correctAnswer: 'A' },
    { question: '¿Que palabra es correcta: "experto" o "esperto"?', optionA: 'Experto', optionB: 'Esperto', correctAnswer: 'A' },
    { question: '¿Cual lleva b o v: "berde" o "verde"?', optionA: 'Verde', optionB: 'Berde', correctAnswer: 'A' },
    { question: '¿Como se escribe "distinto" o "distinto"?', optionA: 'Distinto', optionB: 'Distinto', correctAnswer: 'A' },
    { question: '¿Que palabra tiene h: "echo" o "echo"?', optionA: 'Hago', optionB: 'Ago', correctAnswer: 'A' },
    { question: '¿Cual es correcta: "megusta" o "me gusta"?', optionA: 'Me gusta', optionB: 'Megusta', correctAnswer: 'A' },
  ],
  'ingles-vocabulario': [
    { question: '¿Como se dice "gato" en ingles?', optionA: 'Cat', optionB: 'Dog', correctAnswer: 'A' },
    { question: '¿Que significa "book"?', optionA: 'Libro', optionB: 'Cuaderno', correctAnswer: 'A' },
    { question: '¿Como se escribe "casa" en ingles?', optionA: 'House', optionB: 'Horse', correctAnswer: 'A' },
    { question: '¿Que significa "water"?', optionA: 'Agua', optionB: 'Fuego', correctAnswer: 'A' },
    { question: '¿Como se dice "gracias" en ingles?', optionA: 'Thank you', optionB: 'Please', correctAnswer: 'A' },
    { question: '¿Que significa "friend"?', optionA: 'Amigo', optionB: 'Enemigo', correctAnswer: 'A' },
    { question: '¿Como se dice "escuela" en ingles?', optionA: 'School', optionB: 'House', correctAnswer: 'A' },
    { question: '¿Que significa "happy"?', optionA: 'Feliz', optionB: 'Triste', correctAnswer: 'A' },
    { question: '¿Como se dice "comida" en ingles?', optionA: 'Food', optionB: 'Fruit', correctAnswer: 'A' },
    { question: '¿Que significa "beautiful"?', optionA: 'Hermoso', optionB: 'Feo', correctAnswer: 'A' },
  ],
  'ciencias-cuerpo-humano': [
    { question: '¿Cuantos huesos tiene el cuerpo humano adulto?', optionA: '206', optionB: '300', correctAnswer: 'A' },
    { question: '¿Que organo bombea la sangre?', optionA: 'Corazon', optionB: 'Pulmon', correctAnswer: 'A' },
    { question: '¿Cuantos sentidos tiene el cuerpo humano?', optionA: '5', optionB: '6', correctAnswer: 'A' },
    { question: '¿Que tipo de sangre es universalmente donante?', optionA: 'O negativo', optionB: 'AB positivo', correctAnswer: 'A' },
    { question: '¿Cual es el organo mas grande del cuerpo?', optionA: 'Piel', optionB: 'Higado', correctAnswer: 'A' },
    { question: '¿Que gas necesitamos para respirar?', optionA: 'Oxigeno', optionB: 'Nitrogeno', correctAnswer: 'A' },
    { question: '¿Cuantos dientes tiene un adulto normalmente?', optionA: '32', optionB: '28', correctAnswer: 'A' },
    { question: '¿Que parte del cerebro controla el movimiento?', optionA: 'Cerebelo', optionB: 'Tronco encefalico', correctAnswer: 'A' },
    { question: '¿Cual es la funcion principal de los globulos rojos?', optionA: 'Transportar oxigeno', optionB: 'Combatir infecciones', correctAnswer: 'A' },
    { question: '¿Que organo filtra la sangre?', optionA: 'Rinon', optionB: 'Bazo', correctAnswer: 'A' },
  ],
  'historia-roma': [
    { question: '¿En que ano fundo Romulo Roma?', optionA: '753 a.C.', optionB: '509 a.C.', correctAnswer: 'A' },
    { question: '¿Quien cruzo el Rubicon?', optionA: 'Julio Cesar', optionB: 'Neron', correctAnswer: 'A' },
    { question: '¿Cual fue la forma de gobierno de Roma durante la Republica?', optionA: 'Republica', optionB: 'Monarquia', correctAnswer: 'A' },
    { question: '¿Que emperador hizo legal el cristianismo?', optionA: 'Constantino', optionB: 'Neron', correctAnswer: 'A' },
    { question: '¿Cual era la lengua oficial de Roma?', optionA: 'Latin', optionB: 'Griego', correctAnswer: 'A' },
    { question: '¿Que arena era famosa en Roma para los espectaculos?', optionA: 'Coliseo', optionB: 'Circo Maximo', correctAnswer: 'A' },
    { question: '¿En que ano cayo el Imperio Romano de Occidente?', optionA: '476 d.C.', optionB: '395 d.C.', correctAnswer: 'A' },
    { question: '¿Quien fue el primer emperador romano?', optionA: 'Augusto', optionB: 'Julio Cesar', correctAnswer: 'A' },
    { question: '¿Que ejercito famoso tenia legiones organizadas?', optionA: 'Ejercito romano', optionB: 'Ejercito griego', correctAnswer: 'A' },
    { question: '¿Cual era la estructura politica basica de Roma?', optionA: 'Senado y Asambleas', optionB: 'Rey y Consejo', correctAnswer: 'A' },
  ],
  'quimica-elementos': [
    { question: '¿Cual es el simbolo quimico del agua?', optionA: 'H2O', optionB: 'CO2', correctAnswer: 'A' },
    { question: '¿Que gas es esencial para la combustion?', optionA: 'Oxigeno', optionB: 'Nitrogeno', correctAnswer: 'A' },
    { question: '¿Cual es el elemento quimico mas abundante?', optionA: 'Oxigeno', optionB: 'Carbono', correctAnswer: 'A' },
    { question: '¿Que elemento tiene el simbolo "Fe"?', optionA: 'Hierro', optionB: 'Fluor', correctAnswer: 'A' },
    { question: '¿Cual es el gas mas ligero?', optionA: 'Hidrogeno', optionB: 'Helio', correctAnswer: 'A' },
    { question: '¿Que numero atomico tiene el carbono?', optionA: '6', optionB: '8', correctAnswer: 'A' },
    { question: '¿Que elemento forma parte del aire que respiramos?', optionA: 'Nitrogeno', optionB: 'Oxigeno', correctAnswer: 'A' },
    { question: '¿Cual es el simbolo del sodio?', optionA: 'Na', optionB: 'So', correctAnswer: 'A' },
    { question: '¿Que tipo de enlace compartelectrones?', optionA: 'Covalente', optionB: 'Ionico', correctAnswer: 'A' },
    { question: '¿Cual es el elemento quimico del diamante?', optionA: 'Carbono', optionB: 'Silicio', correctAnswer: 'A' },
  ],
  'matematicas-fracciones': [
    { question: '¿Cual es 1/2 + 1/2?', optionA: '1', optionB: '2', correctAnswer: 'A' },
    { question: '¿Que fraccion es mayor: 1/3 o 1/4?', optionA: '1/3', optionB: '1/4', correctAnswer: 'A' },
    { question: '¿Como se escribe 0.5 como fraccion?', optionA: '1/2', optionB: '1/5', correctAnswer: 'A' },
    { question: '¿Cual es 3/4 de 100?', optionA: '75', optionB: '50', correctAnswer: 'A' },
    { question: '¿Que es un numerador?', optionA: 'El numero de arriba en una fraccion', optionB: 'El numero de abajo en una fraccion', correctAnswer: 'A' },
    { question: '¿Cual es 2/3 + 1/3?', optionA: '1', optionB: '3/6', correctAnswer: 'A' },
    { question: '¿Como se simplifica 4/8?', optionA: '1/2', optionB: '2/4', correctAnswer: 'A' },
    { question: '¿Que fraccion equivale a 25%?', optionA: '1/4', optionB: '1/5', correctAnswer: 'A' },
    { question: '¿Cual es 1/2 - 1/4?', optionA: '1/4', optionB: '1/2', correctAnswer: 'A' },
    { question: '¿Que es un denominador?', optionA: 'El numero de abajo en una fraccion', optionB: 'El numero de arriba en una fraccion', correctAnswer: 'A' },
  ],
  'geografia-continentes': [
    { question: '¿Cuantos continentes hay?', optionA: '7', optionB: '6', correctAnswer: 'A' },
    { question: '¿Cual es el continente mas grande?', optionA: 'Asia', optionB: 'Africa', correctAnswer: 'A' },
    { question: '¿En que continente esta Egipto?', optionA: 'Africa', optionB: 'Asia', correctAnswer: 'A' },
    { question: '¿Cual es el rio mas largo del mundo?', optionA: 'Nilo', optionB: 'Amazonas', correctAnswer: 'A' },
    { question: '¿Que oceano es el mas grande?', optionA: 'Pacifico', optionB: 'Atlantico', correctAnswer: 'A' },
    { question: '¿En que continente esta Brasil?', optionA: 'America del Sur', optionB: 'America del Norte', correctAnswer: 'A' },
    { question: '¿Cual es el pais mas grande del mundo?', optionA: 'Rusia', optionB: 'Canada', correctAnswer: 'A' },
    { question: '¿Que muro famoso dividio Berlin?', optionA: 'Muro de Berlin', optionB: 'Muro de Adriano', correctAnswer: 'A' },
    { question: '¿En que continente esta Australia?', optionA: 'Oceania', optionB: 'Asia', correctAnswer: 'A' },
    { question: '¿Cual es el desierto mas grande del mundo?', optionA: 'Sahara', optionB: 'Gobi', correctAnswer: 'A' },
  ],
  'literatura-generos': [
    { question: '¿Que genero literario cuenta historias imaginarias?', optionA: 'Ficcion', optionB: 'No ficcion', correctAnswer: 'A' },
    { question: '¿Que genero se basa en hechos reales?', optionA: 'Biografia', optionB: 'Novela', correctAnswer: 'A' },
    { question: '¿Que es un cuento?', optionA: 'Una narracion breve', optionB: 'Un poema largo', correctAnswer: 'A' },
    { question: '¿Que genero expresa sentimientos mediante rimas?', optionA: 'Poesia', optionB: 'Prosa', correctAnswer: 'A' },
    { question: '¿Que es un drama?', optionA: 'Una obra escrita para ser representada', optionB: 'Una novela de misterio', correctAnswer: 'A' },
    { question: '¿Que genero presenta personajes y conflictos?', optionA: 'Narrativo', optionB: 'Descriptivo', correctAnswer: 'A' },
    { question: '¿Que es un ensayo?', optionA: 'Un texto que expresa opiniones', optionB: 'Una historia de ficcion', correctAnswer: 'A' },
    { question: '¿Que genero busca informar de manera objetiva?', optionA: 'Informativo', optionB: 'Literario', correctAnswer: 'A' },
    { question: '¿Que es una novela?', optionA: 'Una narracion extensa', optionB: 'Un poema corto', correctAnswer: 'A' },
    { question: '¿Que genero usa el lenguaje figurado?', optionA: 'Metafora', optionB: 'Lenguaje tecnico', correctAnswer: 'A' },
  ],
};

const SIMULATED_PRACTICES: Practice[] = [
  {
    id: 'pub_001',
    code: '847291',
    creatorId: 101,
    creatorName: 'Carlos',
    title: 'Historia de Nicaragua',
    description: 'Practica sobre la historia de Nicaragua desde la colonia hasta la epoca moderna.',
    mode: 'decisiones',
    topic: 'Historia de Nicaragua',
    questions: SIMULATED_QUESTIONS['historia-nicaragua'],
    questionCount: 15,
    createdAt: 1725000000000,
    lastPlayedAt: null,
    isPublic: true,
    playCount: 234,
    correctAnswers: 1890,
    incorrectAnswers: 630,
  },
  {
    id: 'pub_002',
    code: '315674',
    creatorId: 102,
    creatorName: 'Maria',
    title: 'Geometria Basica',
    description: 'Aprende sobre angulos, areas y perimetros con esta practica interactiva.',
    mode: 'lava',
    topic: 'Geometria',
    questions: SIMULATED_QUESTIONS['matematica-geometria'],
    questionCount: 10,
    createdAt: 1724900000000,
    lastPlayedAt: null,
    isPublic: true,
    playCount: 156,
    correctAnswers: 1200,
    incorrectAnswers: 360,
  },
  {
    id: 'pub_003',
    code: '629083',
    creatorId: 103,
    creatorName: 'Pedro',
    title: 'El Sistema Solar',
    description: 'Descubre los planetas y las estrellas del sistema solar.',
    mode: 'decisiones',
    topic: 'Sistema Solar',
    questions: SIMULATED_QUESTIONS['ciencias-sistema-solar'],
    questionCount: 10,
    createdAt: 1724800000000,
    lastPlayedAt: null,
    isPublic: true,
    playCount: 312,
    correctAnswers: 2700,
    incorrectAnswers: 420,
  },
  {
    id: 'pub_004',
    code: '158472',
    creatorId: 104,
    creatorName: 'Ana',
    title: 'Ortografia Espanola',
    description: 'Practica la ortografia con palabras comunes en espanol.',
    mode: 'lava',
    topic: 'Ortografia',
    questions: SIMULATED_QUESTIONS['lengua-ortografia'],
    questionCount: 10,
    createdAt: 1724700000000,
    lastPlayedAt: null,
    isPublic: true,
    playCount: 89,
    correctAnswers: 720,
    incorrectAnswers: 170,
  },
  {
    id: 'pub_005',
    code: '734209',
    creatorId: 105,
    creatorName: 'Luis',
    title: 'Vocabulario en Ingles',
    description: 'Aprende vocabulario basico en ingles con esta practica.',
    mode: 'decisiones',
    topic: 'Ingles Basico',
    questions: SIMULATED_QUESTIONS['ingles-vocabulario'],
    questionCount: 10,
    createdAt: 1724600000000,
    lastPlayedAt: null,
    isPublic: true,
    playCount: 445,
    correctAnswers: 3900,
    incorrectAnswers: 550,
  },
  {
    id: 'pub_006',
    code: '502816',
    creatorId: 106,
    creatorName: 'Sofia',
    title: 'El Cuerpo Humano',
    description: 'Conoce los organos y sistemas del cuerpo humano.',
    mode: 'lava',
    topic: 'Cuerpo Humano',
    questions: SIMULATED_QUESTIONS['ciencias-cuerpo-humano'],
    questionCount: 10,
    createdAt: 1724500000000,
    lastPlayedAt: null,
    isPublic: true,
    playCount: 178,
    correctAnswers: 1560,
    incorrectAnswers: 220,
  },
  {
    id: 'pub_007',
    code: '961347',
    creatorId: 107,
    creatorName: 'Diego',
    title: 'El Imperio Romano',
    description: 'Viaja al pasado y descubre la historia de Roma.',
    mode: 'decisiones',
    topic: 'Historia Roma',
    questions: SIMULATED_QUESTIONS['historia-roma'],
    questionCount: 10,
    createdAt: 1724400000000,
    lastPlayedAt: null,
    isPublic: true,
    playCount: 267,
    correctAnswers: 2100,
    incorrectAnswers: 570,
  },
  {
    id: 'pub_008',
    code: '284750',
    creatorId: 108,
    creatorName: 'Elena',
    title: 'Elementos Quimicos',
    description: 'Aprende sobre los elementos de la tabla periodica.',
    mode: 'lava',
    topic: 'Quimica',
    questions: SIMULATED_QUESTIONS['quimica-elementos'],
    questionCount: 10,
    createdAt: 1724300000000,
    lastPlayedAt: null,
    isPublic: true,
    playCount: 134,
    correctAnswers: 1080,
    incorrectAnswers: 260,
  },
  {
    id: 'pub_009',
    code: '473018',
    creatorId: 109,
    creatorName: 'Carlos',
    title: 'Fracciones y Decimales',
    description: 'Domina las fracciones con esta practica completa.',
    mode: 'decisiones',
    topic: 'Fracciones',
    questions: SIMULATED_QUESTIONS['matematicas-fracciones'],
    questionCount: 10,
    createdAt: 1724200000000,
    lastPlayedAt: null,
    isPublic: true,
    playCount: 201,
    correctAnswers: 1680,
    incorrectAnswers: 330,
  },
  {
    id: 'pub_010',
    code: '618593',
    creatorId: 110,
    creatorName: 'Maria',
    title: 'Continentes del Mundo',
    description: 'Explora los continentes, paises y geografia mundial.',
    mode: 'lava',
    topic: 'Geografia',
    questions: SIMULATED_QUESTIONS['geografia-continentes'],
    questionCount: 10,
    createdAt: 1724100000000,
    lastPlayedAt: null,
    isPublic: true,
    playCount: 389,
    correctAnswers: 3200,
    incorrectAnswers: 690,
  },
  {
    id: 'pub_011',
    code: '390264',
    creatorId: 111,
    creatorName: 'Ana',
    title: 'Generos Literarios',
    description: 'Conoce los diferentes generos de la literatura.',
    mode: 'decisiones',
    topic: 'Literatura',
    questions: SIMULATED_QUESTIONS['literatura-generos'],
    questionCount: 10,
    createdAt: 1724000000000,
    lastPlayedAt: null,
    isPublic: true,
    playCount: 112,
    correctAnswers: 900,
    incorrectAnswers: 220,
  },
  {
    id: 'pub_012',
    code: '856147',
    creatorId: 112,
    creatorName: 'Pedro',
    title: 'Matematica Avanzada',
    description: 'Reto de geometria para nivel avanzado.',
    mode: 'lava',
    topic: 'Matematica',
    questions: SIMULATED_QUESTIONS['matematica-geometria'],
    questionCount: 10,
    createdAt: 1723900000000,
    lastPlayedAt: null,
    isPublic: true,
    playCount: 98,
    correctAnswers: 780,
    incorrectAnswers: 200,
  },
];

const PRACTICES_STORAGE_KEY = 'eduplay_simulated_practices_initialized_v2';

function initSimulatedPractices(existingPractices: Practice[]): Practice[] {
  if (typeof window === 'undefined') return existingPractices;

  try {
    const initialized = localStorage.getItem(PRACTICES_STORAGE_KEY);
    if (initialized) return existingPractices;

    const existingIds = new Set(existingPractices.map((p) => p.id));
    const newPractices = SIMULATED_PRACTICES.filter((p) => !existingIds.has(p.id));
    const merged = [...existingPractices, ...newPractices];

    localStorage.setItem(PRACTICES_STORAGE_KEY, 'true');
    return merged;
  } catch {
    return existingPractices;
  }
}

export { initSimulatedPractices, SIMULATED_PRACTICES };
