export interface QuestionData {
  id: string; category: string; difficulty: 'basic' | 'intermediate' | 'advanced';
  statement: string; optionA: string; optionB: string; correctAnswer: 'A' | 'B'; explanation: string;
}

export const dignidadMujerQuestions: QuestionData[] = [
  { id: 'dm-001', category: 'dignidad-mujer', difficulty: 'basic', statement: '¿Qué significa "dignidad"?', optionA: 'El valor y respeto que toda persona merece por ser humana', optionB: 'Algo que solo tienen las personas famosas o ricas', correctAnswer: 'A', explanation: 'La dignidad es el valor que tiene cada persona simplemente por existir.' },
  { id: 'dm-002', category: 'dignidad-mujer', difficulty: 'basic', statement: '¿Tienen las mujeres los mismos derechos que los hombres?', optionA: 'Sí, todas las personas deben tener los mismos derechos', optionB: 'No, los hombres tienen más derechos que las mujeres', correctAnswer: 'A', explanation: 'Todas las personas tienen los mismos derechos.' },
  { id: 'dm-003', category: 'dignidad-mujer', difficulty: 'basic', statement: '¿Es correcto tratar diferente a una niña que a un niño en la escuela?', optionA: 'No, todos merecen el mismo trato y las mismas oportunidades', optionB: 'Sí, los niños merecen más oportunidades', correctAnswer: 'A', explanation: 'Niñas y niños merecen exactamente las mismas oportunidades.' },
  { id: 'dm-004', category: 'dignidad-mujer', difficulty: 'basic', statement: '¿Puede una mujer ser presidenta o líder de un país?', optionA: 'Sí, las mujeres pueden ocupar cualquier cargo de liderazgo', optionB: 'No, esos cargos son solo para hombres', correctAnswer: 'A', explanation: 'Las mujeres tienen toda la capacidad para liderar.' },
  { id: 'dm-005', category: 'dignidad-mujer', difficulty: 'basic', statement: '¿Quién decide qué quiere estudiar o ser una mujer?', optionA: 'Ella misma, cada persona elige su propio camino', optionB: 'Su familia debe decidir por ella', correctAnswer: 'A', explanation: 'Cada mujer tiene derecho a decidir sobre su propia vida.' },
  { id: 'dm-006', category: 'dignidad-mujer', difficulty: 'basic', statement: '¿Debe una mujer pedir permiso para trabajar?', optionA: 'No, las mujeres pueden trabajar libremente sin pedir permiso', optionB: 'Sí, necesita permiso de un hombre de su familia', correctAnswer: 'A', explanation: 'Las mujeres tienen el derecho de trabajar sin necesidad de pedir autorización.' },
  { id: 'dm-007', category: 'dignidad-mujer', difficulty: 'basic', statement: '¿Las niñas pueden jugar fútbol?', optionA: 'Sí, las niñas pueden jugar cualquier deporte que quieran', optionB: 'No, el fútbol es solo para niños', correctAnswer: 'A', explanation: 'No existen deportes exclusivos para niños o niñas.' },
  { id: 'dm-008', category: 'dignidad-mujer', difficulty: 'basic', statement: '¿Tienen derecho las mujeres a votar?', optionA: 'Sí, tienen el mismo derecho al voto que los hombres', optionB: 'No, las decisiones políticas son solo para hombres', correctAnswer: 'A', explanation: 'El voto femenino es un derecho conquistado.' },
  { id: 'dm-009', category: 'dignidad-mujer', difficulty: 'basic', statement: '¿Es aceptable burlarse de una niña por su apariencia?', optionA: 'No, todas las personas merecen respeto sin importar su apariencia', optionB: 'Sí, a veces es divertido hacer bromas', correctAnswer: 'A', explanation: 'Burlarse de alguien por su apariencia es una falta de respeto.' },
  { id: 'dm-010', category: 'dignidad-mujer', difficulty: 'basic', statement: '¿Puede una mujer ser científica?', optionA: 'Sí, las mujeres pueden destacar en cualquier área de la ciencia', optionB: 'No, la ciencia es un campo principalmente masculino', correctAnswer: 'A', explanation: 'Muchas mujeres han hecho descubrimientos científicos fundamentales.' },
  { id: 'dm-011', category: 'dignidad-mujer', difficulty: 'basic', statement: '¿El respeto hacia las mujeres es opcional?', optionA: 'No, el respeto es un derecho y una obligación hacia todas las personas', optionB: 'Sí, depende de cada quien decidir a quién respetar', correctAnswer: 'A', explanation: 'El respeto no es opcional. Es la base de la convivencia.' },
  { id: 'dm-012', category: 'dignidad-mujer', difficulty: 'basic', statement: '¿Es correcto que un hombre le diga a una mujer qué ropa debe usar?', optionA: 'No, cada persona decide libremente cómo vestirse', optionB: 'Sí, para proteger su imagen ante los demás', correctAnswer: 'A', explanation: 'La forma de vestir es una decisión personal.' },
  { id: 'dm-013', category: 'dignidad-mujer', difficulty: 'basic', statement: '¿Las mujeres pueden viajar solas?', optionA: 'Sí, tienen la misma libertad de movimiento que cualquier persona', optionB: 'No, necesitan ir acompañadas por seguridad', correctAnswer: 'A', explanation: 'Todas las personas tienen derecho a la libre circulación.' },
  { id: 'dm-014', category: 'dignidad-mujer', difficulty: 'basic', statement: '¿Resolver los problemas con violencia es correcto?', optionA: 'No, los conflictos deben resolverse con diálogo y respeto', optionB: 'Sí, a veces es necesario ser violento para ser escuchado', correctAnswer: 'A', explanation: 'La violencia nunca es la solución.' },
  { id: 'dm-015', category: 'dignidad-mujer', difficulty: 'basic', statement: '¿Deben las mujeres participar en las decisiones familiares?', optionA: 'Sí, su opinión es igual de valiosa que la de cualquier otro miembro', optionB: 'No, las decisiones importantes las toman los hombres de la casa', correctAnswer: 'A', explanation: 'Todas las personas tienen derecho a opinar y decidir.' },
  { id: 'dm-100', category: 'dignidad-mujer', difficulty: 'intermediate', statement: '¿Qué es la equidad de género?', optionA: 'Dar a cada persona lo que necesita para tener las mismas oportunidades', optionB: 'Tratar a todas las personas exactamente igual sin considerar sus necesidades', correctAnswer: 'A', explanation: 'La equidad busca que todas las personas tengan las mismas oportunidades.' },
  { id: 'dm-101', category: 'dignidad-mujer', difficulty: 'intermediate', statement: '¿Qué son los estereotipos de género?', optionA: 'Ideas preconcebidas sobre cómo deben comportarse hombres y mujeres', optionB: 'Reglas científicas sobre las diferencias entre hombres y mujeres', correctAnswer: 'A', explanation: 'Los estereotipos son ideas que la sociedad asigna sin base real.' },
  { id: 'dm-102', category: 'dignidad-mujer', difficulty: 'intermediate', statement: '¿Qué significa la frase "brecha salarial de género"?', optionA: 'Que las mujeres ganan menos dinero que los hombres por hacer el mismo trabajo', optionB: 'Que las mujeres trabajan menos horas que los hombres', correctAnswer: 'A', explanation: 'La brecha salarial es la diferencia injusta de sueldo.' },
  { id: 'dm-103', category: 'dignidad-mujer', difficulty: 'intermediate', statement: '¿Contribuye la educación a la igualdad de género?', optionA: 'Sí, porque enseña a respetar y valorar a todas las personas por igual', optionB: 'No, la educación no tiene nada que ver con la igualdad', correctAnswer: 'A', explanation: 'La educación es la herramienta más poderosa para construir la igualdad.' },
  { id: 'dm-104', category: 'dignidad-mujer', difficulty: 'intermediate', statement: '¿Las labores del hogar son responsabilidad exclusiva de las mujeres?', optionA: 'No, son responsabilidad de todas las personas que viven en el hogar', optionB: 'Sí, tradicionalmente las mujeres se encargan de la casa', correctAnswer: 'A', explanation: 'Las tareas del hogar son responsabilidad de todas las personas.' },
];
