'use client';
import { useState } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
export function GameMenuButton() {
  const [open, setOpen] = useState(false);
  const [confirm, setConfirm] = useState(false);
  return (
    <>
      <motion.button whileHover={{ scale: 1.08, backgroundColor: 'rgba(255,255,255,0.25)' }} whileTap={{ scale: 0.94 }} onClick={() => setOpen(true)} style={{ position: 'fixed', top: 14, right: 14, zIndex: 100, width: 44, height: 44, borderRadius: 14, border: 'none', background: 'rgba(255,255,255,0.12)', backdropFilter: 'blur(8px)', color: '#fff', fontSize: 20, cursor: 'pointer', display: 'flex', alignItems: 'center', justifyContent: 'center' }}>☰</motion.button>
      <AnimatePresence>{open && (<><motion.div initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }} onClick={() => { setOpen(false); setConfirm(false); }} style={{ position: 'fixed', inset: 0, zIndex: 99, background: 'rgba(0,0,0,0.4)' }} /><motion.div initial={{ x: 280 }} animate={{ x: 0 }} exit={{ x: 280 }} transition={{ type: 'spring', stiffness: 300, damping: 28 }} style={{ position: 'fixed', top: 0, right: 0, bottom: 0, zIndex: 100, width: 260, background: 'rgba(15,15,25,0.96)', backdropFilter: 'blur(20px)', borderLeft: '1px solid rgba(255,255,255,0.06)', padding: '60px 20px 20px', display: 'flex', flexDirection: 'column', gap: 10 }}><button onClick={() => setConfirm(true)} style={{ width: '100%', padding: '14px 16px', borderRadius: 14, border: 'none', background: 'rgba(255,255,255,0.06)', color: '#fff', fontSize: 15, fontWeight: 600, cursor: 'pointer', textAlign: 'left', display: 'flex', alignItems: 'center', gap: 10 }}>🏠 Volver al menú</button></motion.div></>)}</AnimatePresence>
      <AnimatePresence>{confirm && (<motion.div initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }} style={{ position: 'fixed', inset: 0, zIndex: 110, background: 'rgba(0,0,0,0.55)', backdropFilter: 'blur(6px)', display: 'flex', alignItems: 'center', justifyContent: 'center' }}><motion.div initial={{ scale: 0.9, y: 20, opacity: 0 }} animate={{ scale: 1, y: 0, opacity: 1 }} exit={{ scale: 0.9, opacity: 0 }} style={{ background: 'rgba(22,22,34,0.98)', borderRadius: 22, padding: '28px 24px 20px', maxWidth: 340, width: '88%', textAlign: 'center', border: '1px solid rgba(255,255,255,0.06)' }}><p style={{ color: '#fff', fontSize: 16, fontWeight: 700, margin: '0 0 20px' }}>¿Deseas salir de la partida?</p><div style={{ display: 'flex', gap: 10 }}><button onClick={() => setConfirm(false)} style={{ flex: 1, padding: '13px', borderRadius: 14, border: '1px solid rgba(255,255,255,0.1)', background: 'transparent', color: '#ccc', fontSize: 14, fontWeight: 600, cursor: 'pointer' }}>Cancelar</button><button onClick={() => { window.location.href = '/juegos'; }} style={{ flex: 1, padding: '13px', borderRadius: 14, border: 'none', background: 'linear-gradient(135deg, #FF4B4B, #CC3333)', color: '#fff', fontSize: 14, fontWeight: 700, cursor: 'pointer' }}>Salir</button></div></motion.div></motion.div>)}</AnimatePresence>
    </>
  );
}
