'use client';
import { motion, AnimatePresence } from 'framer-motion';
import { useGameStore } from '@/stores/game.store';
import { characterRigidBody } from '@/shared/refs/characterRef';
import { DECISION_ROAD_CONFIG as CFG } from '@/games/decision-road/config';
export function FeedbackOverlay() {
  const phase = useGameStore((s) => s.phase); const explanation = useGameStore((s) => s.explanation); const retryCount = useGameStore((s) => s.retryCount);
  const selectedDoor = useGameStore((s) => s.selectedDoor); const questions = useGameStore((s) => s.questions); const currentQuestionIndex = useGameStore((s) => s.currentQuestionIndex);
  const showCorrect = phase === 'correctFeedback'; const showIncorrect = phase === 'incorrectFeedback' && !!explanation;
  const maxRetriesReached = retryCount >= CFG.maxRetries; const question = questions[currentQuestionIndex];
  const handleRetry = () => { const store = useGameStore.getState(); const idx = maxRetriesReached ? store.currentQuestionIndex + 1 : store.currentQuestionIndex; const rb = characterRigidBody.current; if (rb) { const doorZ = 12 - idx * 25; rb.setTranslation({ x: 0, y: 2, z: doorZ + 8 }, true); rb.setLinvel({ x: 0, y: 0, z: 0 }, true); } if (maxRetriesReached) { store.resetRetry(); store.advanceQuestion(); store.setPhase('playing'); } else { store.resetRetry(); store.setExplanation(null); store.setPhase('playing'); } };
  const correctAnswer = question && maxRetriesReached ? (question.correctAnswer === 'A' ? question.optionA : question.optionB) : null;
  return (
    <>
      <AnimatePresence>{showCorrect && (<motion.div key="correct" initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }} style={{ position: 'absolute', inset: 0, zIndex: 20, pointerEvents: 'none', display: 'flex', alignItems: 'center', justifyContent: 'center' }}><motion.div initial={{ scale: 0.4, opacity: 0 }} animate={{ scale: 1, opacity: 1 }} transition={{ type: 'spring', stiffness: 280, damping: 16 }} style={{ textAlign: 'center' }}><span style={{ fontSize: 52 }}>🎉</span><p style={{ color: '#fff', fontSize: 26, fontWeight: 800, textShadow: '0 2px 16px rgba(253,219,51,0.7)', margin: '8px 0 4px', fontFamily: "var(--font-baloo), system-ui, sans-serif" }}>Excelente decision!</p><p style={{ color: '#FDF293', fontSize: 15, margin: 0 }}>+25 🏆 &nbsp; +15 💎</p></motion.div></motion.div>)}</AnimatePresence>
      <AnimatePresence>{showIncorrect && explanation && (<motion.div key="incorrect" initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }} style={{ position: 'absolute', inset: 0, zIndex: 25, display: 'flex', alignItems: 'center', justifyContent: 'center', background: 'rgba(0,0,0,0.55)', backdropFilter: 'blur(6px)' }}><motion.div initial={{ scale: 0.85, y: 30, opacity: 0 }} animate={{ scale: 1, y: 0, opacity: 1 }} transition={{ type: 'spring', stiffness: 220, damping: 18 }} style={{ background: 'rgba(255,255,255,0.95)', border: '2px solid rgba(233,73,48,0.3)', borderRadius: 28, padding: '28px 26px 24px', maxWidth: 440, width: '88%', textAlign: 'center', boxShadow: '0 12px 40px rgba(233,73,48,0.15)' }}><span style={{ fontSize: 38 }}>💡</span><p style={{ color: '#E94930', fontSize: 18, fontWeight: 800, margin: '0 0 14px', fontFamily: "var(--font-baloo), system-ui, sans-serif" }}>{maxRetriesReached ? 'La respuesta correcta es:' : 'Esta respuesta no es correcta'}</p>{maxRetriesReached && correctAnswer && (<div style={{ background: 'rgba(253,219,51,0.15)', border: '1px solid rgba(253,219,51,0.3)', borderRadius: 14, padding: '12px 16px', marginBottom: 16, color: '#E5C52E', fontSize: 14, fontWeight: 700 }}>{correctAnswer.toUpperCase()}</div>)}<p style={{ color: '#4A5770', fontSize: 14, lineHeight: 1.6, margin: '0 0 20px' }}>{explanation}</p>{!maxRetriesReached && <p style={{ color: '#A0ADC4', fontSize: 11, marginBottom: 16 }}>Intento {retryCount} de {CFG.maxRetries}</p>}<motion.button whileHover={{ scale: 1.05 }} whileTap={{ scale: 0.95 }} onClick={handleRetry} style={{ width: '100%', padding: '16px', borderRadius: 18, border: 'none', background: 'linear-gradient(135deg, #F087A9, #D96B91)', color: '#fff', fontSize: 17, fontWeight: 800, cursor: 'pointer', fontFamily: "var(--font-baloo), system-ui, sans-serif", boxShadow: '0 4px 16px rgba(240,135,169,0.35)' }}>{maxRetriesReached ? 'Continuar ▶' : 'Intentar nuevamente'}</motion.button></motion.div></motion.div>)}</AnimatePresence>
    </>
  );
}
