'use client';
import { motion, AnimatePresence } from 'framer-motion';
import { useGameStore } from '@/stores/game.store';
export function ResultsScreen() {
  const phase = useGameStore((s) => s.phase); const result = useGameStore((s) => s.result); const show = phase === 'results' && result !== null;
  return (
    <AnimatePresence>{show && result && (<motion.div key="results" initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }} style={{ position: 'absolute', inset: 0, zIndex: 30, display: 'flex', alignItems: 'center', justifyContent: 'center', background: 'rgba(0,0,0,0.7)', backdropFilter: 'blur(8px)' }}><motion.div initial={{ scale: 0.8, y: 60, opacity: 0 }} animate={{ scale: 1, y: 0, opacity: 1 }} transition={{ type: 'spring', stiffness: 200, damping: 18, delay: 0.2 }} style={{ background: 'rgba(25,25,35,0.95)', borderRadius: 28, padding: '32px 28px 28px', maxWidth: 400, width: '90%', border: '1px solid rgba(255,255,255,0.08)', textAlign: 'center' }}><div style={{ fontSize: 44, marginBottom: 8 }}>{['','⭐','⭐⭐','⭐⭐⭐'][result.stars]}</div><p style={{ color: '#FFD93D', fontSize: 24, fontWeight: 800, margin: '0 0 24px' }}>¡Nivel completado!</p><div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 12, marginBottom: 24 }}><StatC label="Correctas" value={`${result.correctAnswers}/${result.totalQuestions}`} color="#4CAF50" /><StatC label="Precisión" value={`${result.accuracy}%`} color="#2196F3" /><StatC label="Copas" value={`+${result.score}`} color="#FFD93D" /><StatC label="XP" value={`+${result.xp}`} color="#7C4DFF" /></div><div style={{ display: 'flex', gap: 12 }}><button onClick={() => { const s = useGameStore.getState(); s.setPhase('playing'); s.setQuestions(s.questions); }} style={{ flex: 1, padding: '14px', borderRadius: 16, border: '1px solid rgba(255,255,255,0.15)', background: 'rgba(255,255,255,0.06)', color: '#ddd', fontSize: 15, fontWeight: 600, cursor: 'pointer' }}>🔄 Repetir</button><button onClick={() => { useGameStore.getState().reset(); window.location.reload(); }} style={{ flex: 1, padding: '14px', borderRadius: 16, border: 'none', background: 'linear-gradient(135deg, #7C4DFF, #651FFF)', color: '#fff', fontSize: 15, fontWeight: 700, cursor: 'pointer' }}>▶ Continuar</button></div></motion.div></motion.div>)}</AnimatePresence>
  );
}
function StatC({ label, value, color }: { label: string; value: string; color: string }) { return (<div style={{ background: 'rgba(255,255,255,0.05)', borderRadius: 14, padding: '12px 8px' }}><p style={{ color: '#999', fontSize: 11, margin: '0 0 4px' }}>{label}</p><p style={{ color, fontSize: 16, fontWeight: 700, margin: 0 }}>{value}</p></div>); }
