'use client';
import { motion, AnimatePresence } from 'framer-motion';
import { useGameStore } from '@/stores/game.store';
export function ResultsScreen() {
  const phase = useGameStore((s) => s.phase); const result = useGameStore((s) => s.result); const show = phase === 'results' && result !== null;
  return (
    <AnimatePresence>{show && result && (<motion.div key="results" initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }} style={{ position: 'absolute', inset: 0, zIndex: 30, display: 'flex', alignItems: 'center', justifyContent: 'center', background: 'rgba(0,0,0,0.6)', backdropFilter: 'blur(8px)' }}><motion.div initial={{ scale: 0.8, y: 60, opacity: 0 }} animate={{ scale: 1, y: 0, opacity: 1 }} transition={{ type: 'spring', stiffness: 200, damping: 18, delay: 0.2 }} style={{ background: 'rgba(255,255,255,0.95)', borderRadius: 32, padding: '32px 28px 28px', maxWidth: 400, width: '90%', border: '2px solid rgba(253,219,51,0.3)', textAlign: 'center', boxShadow: '0 12px 48px rgba(253,219,51,0.2)' }}><div style={{ fontSize: 44, marginBottom: 8 }}>{['','⭐','⭐⭐','⭐⭐⭐'][result.stars]}</div><p style={{ color: '#344054', fontSize: 24, fontWeight: 800, margin: '0 0 24px', fontFamily: "inherit" }}>Nivel completado!</p><div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 12, marginBottom: 24 }}><StatC label="Correctas" value={`${result.correctAnswers}/${result.totalQuestions}`} color="#4CAF50" /><StatC label="Precision" value={`${result.accuracy}%`} color="#30BCE6" /><StatC label="Copas" value={`+${result.score}`} color="#FDDB33" /><StatC label="XP" value={`+${result.xp}`} color="#F087A9" /></div><div style={{ display: 'flex', gap: 12 }}><button onClick={() => { const s = useGameStore.getState(); s.setPhase('playing'); s.setQuestions(s.questions); }} style={{ flex: 1, padding: '14px', borderRadius: 18, border: '2px solid #E4EAF4', background: 'rgba(255,255,255,0.6)', color: '#344054', fontSize: 15, fontWeight: 700, cursor: 'pointer' }}>🔄 Repetir</button><button onClick={() => { useGameStore.getState().reset(); window.location.reload(); }} style={{ flex: 1, padding: '14px', borderRadius: 18, border: 'none', background: 'linear-gradient(135deg, #30BCE6, #1A9FCC)', color: '#fff', fontSize: 15, fontWeight: 800, cursor: 'pointer', fontFamily: "inherit", boxShadow: '0 4px 16px rgba(48,188,230,0.3)' }}>▶ Continuar</button></div></motion.div></motion.div>)}</AnimatePresence>
  );
}
function StatC({ label, value, color }: { label: string; value: string; color: string }) { return (<div style={{ background: '#F8FAFE', borderRadius: 16, padding: '12px 8px' }}><p style={{ color: '#6B7A94', fontSize: 11, margin: '0 0 4px', fontWeight: 700 }}>{label}</p><p style={{ color, fontSize: 16, fontWeight: 800, margin: 0, fontFamily: "inherit" }}>{value}</p></div>); }
